[ftplugin]
_ = '''
    setlocal formatoptions-=ro
'''

html = '''
    setlocal nowrap
'''

diff = '''
    setlocal nowrap
'''

make = '''
    setlocal noexpandtab
'''

qf = '''
    " bnext or bprevious ignore quickfix
    set nobuflisted
'''

lua = '''
    setlocal commentstring=--\ %s
'''

toml = '''
    setlocal commentstring=#\ %s
'''

vim = '''
    setlocal commentstring=\"\ %s
'''

html = '''
    setlocal commentstring=\"\ %s
'''

# " vim: set foldmethod=marker tw=80 sw=4 ts=4 sts =4 sta nowrap et :
