# language setting {{{
# all {{{
[[plugins]]
repo = 'Shougo/neco-syntax'
on_source = 'deoplete.nvim'
# }}}
# golang {{{
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
# }}}
# python {{{
[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = 'python'
# }}}
# php {{{
[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = 'php'

[[plugins]]
repo = 'phpactor/phpactor'
build = 'composer install'
on_ft = 'php'

[[plugins]]
repo = 'kristijanhusak/deoplete-phpactor'
depends = ['deoplete.nvim']
on_ft = 'php'
# }}}
# toml {{{
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
# }}}
# vim {{{
[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'
# }}}
# rust {{{
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_add = '''
    set hidden

    let g:racer_cmd = system('echo -n "$(which racer)"')
    let g:racer_experimental_completer = 1
'''
hook_source = '''
    au FileType rust nmap gd <Plug>(rust-def)
    au FileType rust nmap gs <Plug>(rust-def-split)
    au FileType rust nmap gx <Plug>(rust-def-vertical)
    au FileType rust nmap <leader>gd <Plug>(rust-doc)
'''
# }}}
# javascript {{{
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'
# }}}
# c {{{
[[plugins]]
repo = 'justinmk/vim-syntax-extra'
on_ft = ['c', 'lex', 'yacc']
# }}}
# }}}

# apathy {{{
[[plugins]]
repo = 'tpope/vim-apathy'
on_ft = ['c', 'go']
# }}}

# vim-sayonara (sane buffer/window deletion) {{{
[[plugins]]
repo = 'mhinz/vim-sayonara'
on_cmd = 'Sayonara'
hook_add = '''
    nnoremap <silent> <leader>c :Sayonara!<CR>
    nnoremap <silent> <leader>q :Sayonara<CR>
'''
# }}}

# Gina {{{
[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'
# }}}

# vim-scriptease {{{
[[plugins]]
repo = 'tpope/vim-scriptease'
on_ft = 'vim'
# }}}

# matchit (% enhancement) {{{
[[plugins]]
repo = 'vim-scripts/matchit.zip'
on_ft = ['html', 'vim', 'xml']
# }}}

# nerdtree (file explorer) {{{
[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTreeToggle'
hook_add =  '''
    noremap <F5> :NERDTreeToggle<cr>
    " Open file navigator by default
    
    let NERDTreeMinimalUI = 1
    let NERDTreeDirArrows = 1
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['nerdtree']
# }}}

# tagbar (display tags in window) {{{
[[plugins]]
repo = 'majutsushi/tagbar'	
on_cmd = 'TagbarToggle' 
hook_add = '''
    noremap <F8> :TagbarToggle<cr>
    filetype plugin indent on
    syntax enable
'''
# }}}

# auto-pairs {{{
[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_event = 'InsertEnter'
hook_add = '''
    let g:AutoPairsFlyMode = 0
'''
# }}}

# linux coding style {{{
[[plugins]]
repo = 'vivien/vim-linux-coding-style'
on_cmd = 'LinuxCodingStyle'
# }}}

# vim-autoformat (code formatter) {{{
[[plugins]]
repo = 'Chiel92/vim-autoformat'
on_cmd = 'Autoformat'
hook_add = '''
    noremap <F3> :Autoformat<cr>
    let g:formatters_python = ['autopep8']
    let g:formatters_rust = ['rustfmt']
'''
# }}}

# vim-mundo (undo tree) {{{
[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_cmd = 'MundoToggle'
hook_add = '''
    noremap <F6> :MundoToggle<cr>
'''
# }}}

# vim-gitgutter (show git diff and stages/undoes hunks) {{{
[[plugins]]
repo = 'airblade/vim-gitgutter'
on_if = "isdirectory(getcwd().'/.git/')" # has .git folder
# }}}

# neosnippet (snippet) {{{
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = '''
  imap <silent>L     <Plug>(neosnippet_jump_or_expand)
  smap <silent>L     <Plug>(neosnippet_jump_or_expand)
  xmap <silent>L     <Plug>(neosnippet_expand_target)
  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#enable_completed_snippet = 1
  let g:neosnippet#expand_word_boundary = 1
  " let g:snippets_dir = '~/.vim/snippets/,~/.vim/bundle/snipmate/snippets/'
  let g:neosnippet#snippets_directory = expand('~/.config/config/dein/repos/github.com/Shougo/neosnippet-snippets/neosnippets')
  autocmd MyAutoCmd CompleteDone * call neosnippet#complete_done()
'''
# }}}

# deoplete (autocomplete) {{{
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
'''
hook_source = "exe 'source' $nvimrc.'/config/deoplete.vim'"
# }}}

# denite {{{
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = "exe 'source' $nvimrc.'/config/denite.vim'"
hook_add = '''
    noremap [denite-leader] <Nop>
    nmap ; [denite-leader]
    
    " TODO: Denite outline and ctags setting
    "
    " ctrlp
    nnoremap <silent> <C-p> :<C-u>Denite -mode=normal file_rec<CR>
    
    " list all buffer
    nnoremap <silent> [denite-leader]b :<C-u>Denite -mode=normal buffer<CR>
    
    " 
    nnoremap <silent> [denite-leader]r :<C-u>Denite -refresh -resume -mode=normal -buffer-name=search<CR>
    
    " search in this file (create buffer name called search)
    nnoremap <silent> [denite-leader]/ :<C-u>Denite -buffer-name=search -auto-highlight  -auto-resize line<CR>
    " search globally - search recursively from project root (auto-preview is slowly)
    nnoremap <silent> [denite-leader]g/ :<C-u>Denite -buffer-name=search -mode=normal grep<CR>
    " search current word in the file
    nnoremap <silent> [denite-leader]cr :<C-u>DeniteCursorWord  -mode=normal -buffer-name=search -auto-highlight line<CR><C-R><C-W><CR>
    " search current word globally 
    nnoremap <silent> [denite-leader]gc :<C-u>DeniteCursorWord  -mode=normal -buffer-name=search grep<CR><C-R><C-W><CR>
    " list register 
    nnoremap <silent> [denite-leader]re :<C-u>Denite -mode=normal -buffer-name=list_reg register<CR>
'''
#  file mru source {{{ 
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'
# }}}

# }}}

# vim-asterisk (star improved) {{{
[[plugins]]
repo = 'haya14busa/vim-asterisk'
on_map = '<Plug>(asterisk-'

[[plugins]]
repo = 'haya14busa/is.vim'
on_source = 'vim-asterisk'
hook_add = '''
let g:asterisk#keeppos = 1
map *  <Plug>(asterisk-z*)<Plug>(is-nohl-1)
map #  <Plug>(asterisk-z#)<Plug>(is-nohl-1)
map g* <Plug>(asterisk-gz*)<Plug>(is-nohl-1)
map g# <Plug>(asterisk-gz#)<Plug>(is-nohl-1)
'''
# }}}


# " vim: set foldmethod=marker tw=80 sw=4 ts=4 sts =4 sta nowrap et :
