[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
    set bg=dark
    colorscheme gruvbox
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    let g:airline#extensions#tabline#enabled = 1
    
    " show the airline_tab type is tab or buffer (top right)
    let g:airline#extensions#tabline#show_tab_type = 1
    
    " close symbol (top right)
    let g:airline#extensions#tabline#close_symbol = 'X'
    
    " enable displaying buffers with a single tab 
    " it mean airline_tab type is buffer
    let g:airline#extensions#tabline#show_buffers = 1
    " Show the buffer order with a single tab
    " convient to use <leader>n to switch buffer
    let g:airline#extensions#tabline#buffer_idx_mode = 1
    
    " if airline_tab type is tab
    " convient to use <leader>n to switch tap
    let g:airline#extensions#tabline#tab_nr_type = 1 
    
    " disable show split information on top right
    let g:airline#extensions#tabline#show_splits = 0
    
    nmap <leader>1 <Plug>AirlineSelectTab1
    nmap <leader>2 <Plug>AirlineSelectTab2
    nmap <leader>3 <Plug>AirlineSelectTab3
    nmap <leader>4 <Plug>AirlineSelectTab4
    nmap <leader>5 <Plug>AirlineSelectTab5
    nmap <leader>6 <Plug>AirlineSelectTab6
    nmap <leader>7 <Plug>AirlineSelectTab7
    nmap <leader>8 <Plug>AirlineSelectTab8
    nmap <leader>9 <Plug>AirlineSelectTab9
'''



[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
    let g:rainbow_active = 1 
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'simnalamburt/vim-mundo'
hook_add = '''
    set undofile
    set undodir=$HOME/.config/nvim/undo
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
'''


[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    noremap [denite-leader] <Nop>
    nmap ; [denite-leader]
    
    
    call denite#custom#option('_', {
        \ 'prompt': 'Î»:',
        \ 'winheight': 10,
        \ 'updatetime': 1,
        \ 'auto_resize': 1,
        \ 'source_names': 'short',
        \ 'empty': 0,
        \ 'auto-accel': 1,
        \})
    "   'vertical_preview': 1, " use it when needed
    
    
    
    " TODO: Denite outline and ctags setting
    "
    " ctrlp
    nnoremap <silent> <C-p> :<C-u>Denite -mode=normal file_rec<CR>
    
    " list all buffer
    nnoremap <silent> [denite-leader]b :<C-u>Denite -mode=normal buffer<CR>
    
    " 
    nnoremap <silent> [denite-leader]r :<C-u>Denite -buffer-name=search -resume -mode=normal<CR>
    
    " search in this file (create buffer name called search)
    nnoremap <silent> [denite-leader]/ :<C-u>Denite -buffer-name=search -auto-highlight  -auto-resize line<CR>
    " search globally - search recursively from project root (auto-preview is slowly)
    nnoremap <silent> [denite-leader]g/ :<C-u>Denite -buffer-name=search -mode=normal grep<CR>
    " search current word in the file
    nnoremap <silent> [denite-leader]cr :<C-u>DeniteCursorWord  -mode=normal -buffer-name=search -auto-highlight line<CR><C-R><C-W><CR>
    " search current word globally 
    nnoremap <silent> [denite-leader]gc :<C-u>DeniteCursorWord  -mode=normal -buffer-name=search grep<CR><C-R><C-W><CR>
    " make the buffer named search not quit after the action is excuted
    call denite#custom#option('search', {
        \ 'quit': 0,
        \})
    
    " denite-key mapping
    call denite#custom#map('insert', 'jk', '<denite:enter_mode:normal>')
    call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>')
    call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>')
    
    call denite#custom#map('insert', "<C-t>", '<denite:do_action:tabopen>')
    call denite#custom#map('insert', "<C-v>", '<denite:do_action:vsplit>')
    call denite#custom#map('normal', "vs", '<denite:do_action:vsplit>')
    call denite#custom#map('normal', "sp", '<denite:do_action:split>')
    call denite#custom#map('normal', "<C-h>", '<denite:wincmd:h>')
    call denite#custom#map('normal', "<C-j>", '<denite:wincmd:j>')
    call denite#custom#map('normal', "<C-k>", '<denite:wincmd:k>')
    call denite#custom#map('normal', "<C-l>", '<denite:wincmd:l>')
    " customize ignore globs
    call denite#custom#source('grep', 'matchers', ['matcher_ignore_globs'])
    call denite#custom#source('line', 'matchers', ['matcher_ignore_globs', 'matcher_regexp'])
    call denite#custom#source('file_rec', 'matchers', ['matcher_fuzzy','matcher_ignore_globs'])
    
    call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
          \ [
          \ '.git/', 'build/', '__pycache__/',
          \ 'images/', '*.o', '*.make',
          \ '*.min.*',
          \ 'img/', 'fonts/',
          \ 'tags', 'cscope*'])
    
'''
