# language setting {{{
# all {{{
[[plugins]]
repo = 'Shougo/neco-syntax'
on_source = 'deoplete.nvim'
# }}}
# golang {{{
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
build = 'GoInstallBinaries'
hook_add = '''
    let g:go_def_mapping_enabled = 0
    autocmd Filetype go nmap <buffer> gd <Plug>(go-def)
    autocmd Filetype go nmap <buffer> gD <Plug>(go-describe)
    autocmd Filetype go nmap <buffer> gR <Plug>(go-rename)
    autocmd Filetype go nmap <buffer> gr <Plug>(go-referrers)
    let g:go_snippet_engine = 'neosnippet'
    let g:go_metalinter_command = "golangci-lint"
    let g:go_metalinter_autosave_enabled = ['vet', 'errcheck']
    let g:go_metalinter_autosave = 1
    let g:go_jump_to_error = 0

    let g:go_echo_go_info = 0
    let g:go_auto_type_info = 1
    let g:go_auto_sameids = 1
    let g:go_fmt_command = "goimports"
    let g:go_fmt_autosave = 1
    let g:go_guru_scope = ["..."]
    let g:go_gopls_use_placeholders = 'gopls'

    autocmd Filetype go nnoremap <buffer> <f16> <cmd>GoTest<cr>
    autocmd Filetype go nnoremap <buffer> <f17> <cmd>GoBuild<cr>
    autocmd Filetype go nnoremap <buffer> <f18> <cmd>GoRun<cr>
'''
# }}}
# python {{{
[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = 'python'
# }}}
# vim {{{
# vim source for deoplete
[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'
# }}}
# rust {{{
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
    let $RUST_SRC_PATH =
                \ system('echo -n "$(rustc --print sysroot)"').
                \ "/lib/rustlib/src/rust/src"
'''

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_add = '''
    set hidden

    let g:racer_cmd = system('echo -n "$(which racer)"')
    let g:racer_experimental_completer = 1
'''
hook_source = '''
    au FileType rust nmap gd <Plug>(rust-def)
    au FileType rust nmap gs <Plug>(rust-def-split)
    au FileType rust nmap gx <Plug>(rust-def-vertical)
    au FileType rust nmap <leader>gd <Plug>(rust-doc)
'''
# }}}
# javascript, typescript {{{
[[plugins]]
repo = 'mhartington/nvim-typescript'
build = './install.sh'
on_ft = ['javascript', 'typescript']
hook_add = '''
    let g:nvim_typescript#server_path = 'tsserver'
    let g:nvim_typescript#javascript_support = 1
    let g:nvim_typescript#type_info_on_hold = 1
'''
#}}}
# }}}

# apathy {{{
[[plugins]]
repo = 'tpope/vim-apathy'
on_ft = ['c', 'go']
# }}}

# vim-sayonara (sane buffer/window deletion) {{{
[[plugins]]
repo = 'mhinz/vim-sayonara'
on_cmd = 'Sayonara'
hook_add = '''
    let g:sayonara_filetypes = {
                \ 'defx': 'call defx#call_action("quit")',
                \ 'tagbar': 'TagbarClose'
                \ }
    nnoremap <silent> <leader>c <cmd>Sayonara!<CR>
    nnoremap <silent> <leader>q <cmd>Sayonara<CR>
'''
# }}}

# Gina {{{
[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'
hook_source = '''
    exe 'source' $NVIMRC.'/config/gina.vim'
    nmap dp <Plug>(gina-diffput)
    nmap do <Plug>(gina-diffget)
'''
# }}}

# vim-scriptease {{{
[[plugins]]
repo = 'tpope/vim-scriptease'
on_ft = 'vim'
# }}}

# Defx {{{
[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
hook_source = "exe 'source' $NVIMRC.'/config/defx.vim'"
hook_add = '''
    autocmd MyAutoCmd BufLeave,BufWinLeave  \[defx\]* call defx#call_action('add_session')
    autocmd MyAutoCmd FileType defx call MyDefxKeySetup()
    noremap <silent><F4> <cmd>Defx -session-file='/tmp/defx_session' -buffer-name="defx"<CR>
'''

[[plugins]]
repo = 'kristijanhusak/defx-git'
on_source = ['defx.nvim']
hook_add = '''
    autocmd MyAutoCmd FileType defx nmap <buffer><silent> [c <Plug>(defx-git-prev)
    autocmd MyAutoCmd FileType defx nmap <buffer><silent> ]c <Plug>(defx-git-next)
'''
hook_source = '''
    call defx#custom#column('git', 'raw_mode', 1)
    call defx#custom#column('git', 'max_indicator_width', 2)
'''
# }}}

# tagbar (display tags in window) {{{
[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = 'TagbarToggle'
hook_add = '''
    let g:tagbar_ctags_bin = system('echo -n "$(which ctags)"')
    noremap <F8> <cmd>TagbarToggle<cr>
    filetype plugin indent on
    syntax enable
    let g:tagbar_type_go = {
	\ 'ctagstype' : 'go',
	\ 'kinds'     : [
		\ 'p:package',
		\ 'i:imports:1',
		\ 'c:constants',
		\ 'v:variables',
		\ 't:types',
		\ 'n:interfaces',
		\ 'w:fields',
		\ 'e:embedded',
		\ 'm:methods',
		\ 'r:constructor',
		\ 'f:functions'
	\ ],
	\ 'sro' : '.',
	\ 'kind2scope' : {
		\ 't' : 'ctype',
		\ 'n' : 'ntype'
	\ },
	\ 'scope2kind' : {
		\ 'ctype' : 't',
		\ 'ntype' : 'n'
	\ },
	\ 'ctagsbin'  : 'gotags',
	\ 'ctagsargs' : '-sort -silent'
\ }
'''
# }}}

# auto-pairs {{{
[[plugins]]
repo = 'Raimondi/delimitMate'
on_event = 'InsertEnter'
hook_add = '''
    let g:delimitMate_expand_space = 1
    let g:delimitMate_smart_quotes = 1
    let g:delimitMate_nesting_quotes = ['"', "'"]
'''
# }}}

# linux coding style {{{
[[plugins]]
repo = 'vivien/vim-linux-coding-style'
on_cmd = 'LinuxCodingStyle'
# }}}

# vim-autoformat (code formatter) {{{
[[plugins]]
repo = 'Chiel92/vim-autoformat'
on_cmd = 'Autoformat'
hook_add = '''
    noremap <F3> <cmd>Autoformat<cr>
    let g:formatters_python = ['autopep8']
    let g:formatters_rust = ['rustfmt']
'''
# }}}

# undo tree {{{
repo = 'mbbill/undotree'
on_cmd = 'UndotreeToggle'
hook_add = '''
    nnoremap <F6> <cmd>UndotreeToggle<cr>
'''
# }}}

# vim-sinify (show git diff and stages/undoes hunks) {{{
[[plugins]]
repo = 'mhinz/vim-signify'
on_if = "isdirectory(getcwd().'/.git/')" # has .git folder
hook_source = '''
    exe 'source' $NVIMRC.'/config/signify.vim'
'''
# }}}

# neosnippet (snippet) {{{
[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_add = '''
    let g:neosnippet#enable_snipmate_compatibility = 1
    let g:neosnippet#enable_completed_snippet = 1
    let g:neosnippet#expand_word_boundary = 1
	let g:neosnippet#enable_complete_done = 1
    let g:neosnippet#snippets_directory = expand('$NVIMRC/neosnippets')

'''
# }}}

# deoplete (autocomplete) {{{
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = '''
    exe 'source' $NVIMRC.'/config/deoplete.vim'
    call deoplete#enable()
'''
# }}}

# deoplete-tag (tag source for deoplete) {{{
[[plugins]]
repo = 'deoplete-plugins/deoplete-tag'
on_source = 'deoplete.nvim'
# }}}

# denite {{{
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = "exe 'source' $NVIMRC.'/config/denite.vim'"
hook_add = '''
    noremap [denite-leader] <Nop>
    nmap ; [denite-leader]

    autocmd FileType denite call MyDeniteKeySetup()

    " file mru
    nnoremap <silent> [denite-leader]fu :<C-u>Denite -start-filter file_mru<CR>

    " list all buffer
    nnoremap <silent> [denite-leader]b :<C-u>Denite buffer<CR>

    " search in this file (create buffer name called search)
    nnoremap <silent> [denite-leader]/ :<C-u>Denite -auto-resize -start-filter line<CR>

    " search globally - search recursively from project root (auto-preview is slowly)
    nnoremap <silent> [denite-leader]g/ :<C-u>Denite -buffer-name=search grep<CR>

    " search current word in the file
    nnoremap <silent> [denite-leader]cr :<C-u>DeniteCursorWord line<CR><C-R><C-W><CR>
    " search current word globally
    nnoremap <silent> [denite-leader]gc :<C-u>DeniteCursorWord -buffer-name=search grep<CR><C-R><C-W><CR>

    " list register
    nnoremap <silent> [denite-leader]r
                \ :<C-u>Denite -buffer-name=register
                \ neoyank register<CR>
    xnoremap <silent> [denite-leader]r
                \ :<C-u>Denite -default-action=replace -buffer-name=register
                \ neoyank register<CR>
'''
#  file mru source {{{
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'
# }}}

# neoyank source {{{
[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = 'denite.nvim'

# }}}
# }}}

# vim-asterisk (star improved) {{{
[[plugins]]
repo = 'haya14busa/vim-asterisk'
on_map = '<Plug>(asterisk-'

[[plugins]]
repo = 'haya14busa/is.vim'
on_map = '<Plug>(is-'
hook_add = '''
    let g:asterisk#keeppos = 1
    map *  <Plug>(asterisk-z*)<Plug>(is-nohl-1)
    map #  <Plug>(asterisk-z#)<Plug>(is-nohl-1)
    map g* <Plug>(asterisk-gz*)<Plug>(is-nohl-1)
    map g# <Plug>(asterisk-gz#)<Plug>(is-nohl-1)
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_map = '<Plug>(anzu-'
hook_add = '''
    map n <Plug>(is-nohl)<Plug>(anzu-n-with-echo)zzzv
    map N <Plug>(is-nohl)<Plug>(anzu-N-with-echo)zzzv
    " nmap n <Plug>(anzu-mode-n)
    " nmap N <Plug>(anzu-mode-N)
'''
# }}}

#  vim-better-whitespace {{{
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
on_cmd = ['ToggleWhitespace', 'StripWhitespace', 'EnableWhitespace']
hook_add = '''
    let g:better_whitespace_ctermcolor='3'
    let g:better_whitespace_guicolor = '#c8e6c9'
    let g:better_whitespace_filetypes_blacklist = ['defx', 'help', 'qf', 'diff']
    nnoremap <silent><expr><F5> exists("g:better_whitespace_enabled") ? ':ToggleWhitespace<cr>' : ':EnableWhitespace<cr>'
    " <S-F5> for stripping white space
    nnoremap <F17> <cmd>StripWhitespace<cr>
'''
# }}}

# cscope in quickfixwindow {{{
[[plugins]]
repo = 'ronakg/quickr-cscope.vim'
on_cmd = ['cs', 'cscope']
hook_add = '''
    let g:quickr_cscope_keymaps = 0
    nmap <C-s>s <plug>(quickr_cscope_symbols)
    nmap <C-s>g <plug>(quickr_cscope_global)
    nmap <C-s>c <plug>(quickr_cscope_callers)
    nmap <C-s>f <plug>(quickr_cscope_files)
    nmap <C-s>i <plug>(quickr_cscope_includes)
    nmap <C-s>t <plug>(quickr_cscope_text)
    nmap <C-s>e <plug>(quickr_cscope_egrep)
    nmap <C-s>d <plug>(quickr_cscope_functions)
'''
# }}}

#  tabnine deoplete source {{{
[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'
on_source = 'deoplete.nvim'
# }}}

# rtf highlight {{{
[[plugins]]
repo = 'dharanasoft/rtf-highlight'
on_cmd = 'RTFHighlight'
# }}}

# focus programming {{{
[[plugins]]
repo = 'junegunn/goyo.vim'
on_cmd = ['Goyo', 'Goyo!']
hook_add = '''
    " Goyo toggle
    noremap <silent><expr> <F2> exists('#goyo') ? '<cmd>Goyo!<cr>':'<cmd>Goyo<cr>'
'''

[[plugins]]
repo = 'junegunn/limelight.vim'
on_cmd = ['Limelight', 'Limelight!']
on_map = '<Plug>(Limelight)'
hook_add = '''
    " <S-F2> Limeligh toggle
    noremap <silent><expr> <F14> !exists('#goyo') ? ''
                \ : exists('#limelight') ? '<cmd>Limelight!<cr>'
                \ : '<cmd>Limelight<cr>'
    autocmd! User GoyoLeave Limelight!
'''
# }}}

# qfreplace {{{
repo = 'thinca/vim-qfreplace'
on_cmd = 'Qfreplace'
# }}}

# vim-easy-align {{{
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = 'EasyAlign'
on_map = '<Plug>(EasyAlign)'
hook_add = '''
    xmap ga <Plug>(EasyAlign)
    nmap ga <Plug>(EasyAlign)
'''

# }}}

# " vim: set foldmethod=marker tw=80 sw=4 ts=4 sts =4 sta nowrap et :
